import { env } from "cloudflare:workers";
type P={x:number;y:number;alive:boolean;power:number;range:number};
type B={x:number;y:number;owner:"p1"|"p2";at:number;range:number};
type S={tiles:string[][];players:{p1:P;p2:P};bombs:B[];flames:{x:number;y:number}[];status:string;updatedAt:number};
const dirs=[{x:0,y:-1},{x:1,y:0},{x:0,y:1},{x:-1,y:0}];
function tick(s:S){const now=Date.now(),boom=s.bombs.filter(b=>b.at<=now);s.bombs=s.bombs.filter(b=>b.at>now);s.flames=[];for(const b of boom){s.flames.push({x:b.x,y:b.y});for(const d of dirs)for(let i=1;i<=b.range;i++){const x=b.x+d.x*i,y=b.y+d.y*i,t=s.tiles[y]?.[x];if(!t||t==="wall")break;s.flames.push({x,y});if(t==="crate"){s.tiles[y][x]=((x*7+y*13+Math.floor(b.at/1000))%6===0)?"power":((x*11+y*5+Math.floor(b.at/1000))%7===0)?"range":"floor";break}}}for(const id of ["p1","p2"] as const)if(s.flames.some(f=>f.x===s.players[id].x&&f.y===s.players[id].y))s.players[id].alive=false;if(!s.players.p1.alive||!s.players.p2.alive)s.status="ended";s.updatedAt=now;return s}
async function load(code:string){return env.DB.prepare("SELECT state,version FROM game_rooms WHERE code=?").bind(code).first<{state:string;version:number}>()}
export async function GET(_:Request,{params}:{params:Promise<{code:string}>}){const {code}=await params,row=await load(code.toUpperCase());if(!row)return Response.json({error:"없는 방이에요"},{status:404});const state=tick(JSON.parse(row.state) as S);await env.DB.prepare("UPDATE game_rooms SET state=?,version=version+1,updated_at=? WHERE code=? AND version=?").bind(JSON.stringify(state),Date.now(),code.toUpperCase(),row.version).run();return Response.json({state})}
export async function POST(req:Request,{params}:{params:Promise<{code:string}>}){const {code}=await params,c=code.toUpperCase(),body=await req.json() as {role?:"p1"|"p2";action?:string;dx?:number;dy?:number};for(let tries=0;tries<3;tries++){const row=await load(c);if(!row)return Response.json({error:"없는 방이에요"},{status:404});const s=tick(JSON.parse(row.state) as S),role=body.role;if(!role)return Response.json({error:"role required"},{status:400});if(body.action==="join"){if(s.status==="waiting")s.status="playing"}else if(s.status==="playing"&&s.players[role].alive){const p=s.players[role];if(body.action==="move"){const x=p.x+Math.sign(body.dx||0),y=p.y+Math.sign(body.dy||0),t=s.tiles[y]?.[x];if(t&&t!=="wall"&&t!=="crate"&&!s.bombs.some(b=>b.x===x&&b.y===y)){p.x=x;p.y=y;if(t==="power"){p.power++;s.tiles[y][x]="floor"}if(t==="range"){p.range++;s.tiles[y][x]="floor"}}}if(body.action==="bomb"&&s.bombs.filter(b=>b.owner===role).length<p.power&&!s.bombs.some(b=>b.x===p.x&&b.y===p.y))s.bombs.push({x:p.x,y:p.y,owner:role,at:Date.now()+1800,range:p.range})}const out=await env.DB.prepare("UPDATE game_rooms SET state=?,version=version+1,updated_at=? WHERE code=? AND version=?").bind(JSON.stringify(s),Date.now(),c,row.version).run();if(out.meta.changes)return Response.json({state:s})}return Response.json({error:"잠시 후 다시 해주세요"},{status:409})}
