import { env } from "cloudflare:workers";
type P={x:number;y:number;alive:boolean;power:number;range:number};type B={x:number;y:number;owner:"p1"|"p2";at:number;range:number};type S={mode?:string;seed?:number;destroyed?:Record<string,number>;tiles?:string[][];players:{p1:P;p2:P};bombs:B[];flames:{x:number;y:number}[];status:string;ai?:boolean;createdAt?:number;lastAiAt?:number;updatedAt:number};
const dirs=[{x:0,y:-1},{x:1,y:0},{x:0,y:1},{x:0,y:-1},{x:-1,y:0}];
function hash(x:number,y:number,seed=1){let n=Math.imul(x,374761393)+Math.imul(y,668265263)+seed*69069;n=(n^(n>>>13))*1274126177;return(n^(n>>>16))>>>0}
function tile(s:S,x:number,y:number){if(s.mode!=="random")return s.tiles?.[y]?.[x]||"wall";const near=Object.values(s.players).some(p=>Math.abs(p.x-x)+Math.abs(p.y-y)<=2);if(x%2===0&&y%2===0)return"wall";if(near)return"floor";if(s.destroyed?.[`${x},${y}`])return"floor";return hash(x,y,s.seed)%100<58?"crate":"floor"}
function tick(s:S){const now=Date.now();if(s.mode==="random"&&s.status==="waiting"&&now-(s.createdAt||now)>3500){s.ai=true;s.status="playing"}if(s.destroyed)for(const [k,t] of Object.entries(s.destroyed))if(t<=now)delete s.destroyed[k];const boom=s.bombs.filter(b=>b.at<=now);s.bombs=s.bombs.filter(b=>b.at>now);s.flames=[];for(const b of boom){s.flames.push({x:b.x,y:b.y});for(const d of dirs.slice(1))for(let i=1;i<=b.range;i++){const x=b.x+d.x*i,y=b.y+d.y*i,t=tile(s,x,y);if(t==="wall")break;s.flames.push({x,y});if(t==="crate"){if(s.mode==="random")(s.destroyed||={})[`${x},${y}`]=now+12000;else if(s.tiles)s.tiles[y][x]=((x*7+y*13+Math.floor(b.at/1000))%6===0)?"power":((x*11+y*5+Math.floor(b.at/1000))%7===0)?"range":"floor";break}}}if(s.ai&&s.status==="playing"&&now-(s.lastAiAt||0)>420){const a=s.players.p2,target=s.players.p1,ordered=[...dirs.slice(1)].sort((u,v)=>(Math.abs(a.x+u.x-target.x)+Math.abs(a.y+u.y-target.y))-(Math.abs(a.x+v.x-target.x)+Math.abs(a.y+v.y-target.y)));const move=ordered.find(d=>tile(s,a.x+d.x,a.y+d.y)==="floor"&&!s.bombs.some(b=>b.x===a.x+d.x&&b.y===a.y+d.y));if(move&&hash(a.x,a.y,Math.floor(now/500))%100<72){a.x+=move.x;a.y+=move.y}const distance=Math.abs(a.x-target.x)+Math.abs(a.y-target.y);if(distance<7&&!s.bombs.some(b=>b.owner==="p2")&&hash(a.x,a.y,Math.floor(now/1000))%4===0)s.bombs.push({x:a.x,y:a.y,owner:"p2",at:now+1900,range:a.range});s.lastAiAt=now}for(const id of ["p1","p2"] as const)if(s.flames.some(f=>f.x===s.players[id].x&&f.y===s.players[id].y))s.players[id].alive=false;if(!s.players.p1.alive||!s.players.p2.alive)s.status="ended";s.updatedAt=now;return s}
async function load(code:string){return env.DB.prepare("SELECT state,version FROM game_rooms WHERE code=?").bind(code).first<{state:string;version:number}>()}
export async function GET(_:Request,{params}:{params:Promise<{code:string}>}){const {code}=await params,row=await load(code.toUpperCase());if(!row)return Response.json({error:"없는 방이에요"},{status:404});const state=tick(JSON.parse(row.state));await env.DB.prepare("UPDATE game_rooms SET state=?,version=version+1,updated_at=? WHERE code=? AND version=?").bind(JSON.stringify(state),Date.now(),code.toUpperCase(),row.version).run();return Response.json({state})}
export async function POST(req:Request,{params}:{params:Promise<{code:string}>}){const {code}=await params,c=code.toUpperCase(),body=await req.json() as {role?:"p1"|"p2";action?:string;dx?:number;dy?:number};for(let tries=0;tries<3;tries++){const row=await load(c);if(!row)return Response.json({error:"없는 방이에요"},{status:404});const s=tick(JSON.parse(row.state) as S),role=body.role;if(!role)return Response.json({error:"role required"},{status:400});if(body.action==="join"&&s.mode!=="random"){if(s.status==="waiting")s.status="playing"}else if(s.status==="playing"&&s.players[role].alive){const p=s.players[role];if(body.action==="move"){const x=p.x+Math.sign(body.dx||0),y=p.y+Math.sign(body.dy||0),t=tile(s,x,y);if(t!=="wall"&&t!=="crate"&&!s.bombs.some(b=>b.x===x&&b.y===y)){p.x=x;p.y=y;if(t==="power"&&s.tiles){p.power++;s.tiles[y][x]="floor"}if(t==="range"&&s.tiles){p.range++;s.tiles[y][x]="floor"}}}if(body.action==="bomb"&&s.bombs.filter(b=>b.owner===role).length<p.power&&!s.bombs.some(b=>b.x===p.x&&b.y===p.y))s.bombs.push({x:p.x,y:p.y,owner:role,at:Date.now()+1800,range:p.range})}const out=await env.DB.prepare("UPDATE game_rooms SET state=?,version=version+1,updated_at=? WHERE code=? AND version=?").bind(JSON.stringify(s),Date.now(),c,row.version).run();if(out.meta.changes)return Response.json({state:s})}return Response.json({error:"잠시 후 다시 해주세요"},{status:409})}
