import { env } from "cloudflare:workers";
type P={x:number;y:number;power:number;range:number;seen:number};type B={x:number;y:number;owner:string;at:number;range:number};type S={seed:number;players:Record<string,P>;bombs:B[];flames:{x:number;y:number}[];destroyed:Record<string,number>;clear:Record<string,boolean>;updatedAt:number};
const WORLD="ENDLESS_WORLD_V1",dirs=[{x:0,y:-1},{x:1,y:0},{x:0,y:1},{x:-1,y:0}];
function hash(x:number,y:number,seed=1){let n=Math.imul(x,374761393)+Math.imul(y,668265263)+seed*69069;n=(n^(n>>>13))*1274126177;return(n^(n>>>16))>>>0}
function tile(s:S,x:number,y:number){if(x%2===0&&y%2===0)return"wall";if(s.clear[`${x},${y}`]||s.destroyed[`${x},${y}`])return"floor";return hash(x,y,s.seed)%100<58?"crate":"floor"}
function clearSpawn(s:S,x:number,y:number){for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)if(Math.abs(dx)+Math.abs(dy)<=2)s.clear[`${x+dx},${y+dy}`]=true}
function spawn(s:S){for(let i=0;i<200;i++){const x=Math.floor(Math.random()*400-200)*2+1,y=Math.floor(Math.random()*400-200)*2+1;if(Object.values(s.players).every(p=>Math.abs(p.x-x)+Math.abs(p.y-y)>12)){clearSpawn(s,x,y);return{x,y}}}return{x:1,y:1}}
function fresh():S{return{seed:482771,players:{},bombs:[],flames:[],destroyed:{},clear:{},updatedAt:Date.now()}}
function tick(s:S){const now=Date.now();for(const[k,t]of Object.entries(s.destroyed))if(t<=now)delete s.destroyed[k];for(const[k,p]of Object.entries(s.players))if(now-p.seen>45000)delete s.players[k];const boom=s.bombs.filter(b=>b.at<=now);s.bombs=s.bombs.filter(b=>b.at>now);s.flames=[];for(const b of boom){s.flames.push({x:b.x,y:b.y});for(const d of dirs)for(let i=1;i<=b.range;i++){const x=b.x+d.x*i,y=b.y+d.y*i,t=tile(s,x,y);if(t==="wall")break;s.flames.push({x,y});if(t==="crate"){s.destroyed[`${x},${y}`]=now+12000;break}}}for(const p of Object.values(s.players))if(s.flames.some(f=>f.x===p.x&&f.y===p.y)){const n=spawn(s);p.x=n.x;p.y=n.y}return s}
async function load(){const row=await env.DB.prepare("SELECT state,version FROM game_rooms WHERE code=?").bind(WORLD).first<{state:string;version:number}>();if(row)return{state:JSON.parse(row.state)as S,version:row.version};const s=fresh();await env.DB.prepare("INSERT OR IGNORE INTO game_rooms(code,state,version,updated_at) VALUES(?,?,0,?)").bind(WORLD,JSON.stringify(s),Date.now()).run();return{state:s,version:0}}
async function save(s:S,version:number){s.updatedAt=Date.now();return env.DB.prepare("UPDATE game_rooms SET state=?,version=version+1,updated_at=? WHERE code=? AND version=?").bind(JSON.stringify(s),s.updatedAt,WORLD,version).run()}
export async function GET(req:Request){const token=new URL(req.url).searchParams.get("token")?.slice(0,36);if(!token)return Response.json({error:"token required"},{status:400});for(let i=0;i<3;i++){const row=await load(),s=tick(row.state),now=Date.now();if(!s.players[token]){const n=spawn(s);s.players[token]={...n,power:1,range:2,seen:now}}else s.players[token].seen=now;const out=await save(s,row.version);if(out.meta.changes)return Response.json({state:s,token})}return Response.json({error:"retry"},{status:409})}
export async function POST(req:Request){const body=await req.json()as{token?:string;action?:string;dx?:number;dy?:number},token=body.token?.slice(0,36);if(!token)return Response.json({error:"token required"},{status:400});for(let i=0;i<3;i++){const row=await load(),s=tick(row.state),p=s.players[token];if(!p)return Response.json({error:"rejoin"},{status:409});p.seen=Date.now();if(body.action==="move"){const x=p.x+Math.sign(body.dx||0),y=p.y+Math.sign(body.dy||0),t=tile(s,x,y);if(t==="floor"&&!s.bombs.some(b=>b.x===x&&b.y===y)){p.x=x;p.y=y}}if(body.action==="bomb"&&s.bombs.filter(b=>b.owner===token).length<p.power&&!s.bombs.some(b=>b.x===p.x&&b.y===p.y))s.bombs.push({x:p.x,y:p.y,owner:token,at:Date.now()+1800,range:p.range});const out=await save(s,row.version);if(out.meta.changes)return Response.json({state:s})}return Response.json({error:"retry"},{status:409})}
